using System;
using System.ComponentModel;
using BH.oM.Base;
using Newtonsoft.Json;

namespace BH.oM.Adapters.EnergyPlus.SurfaceConstructionElements
{
    [Description("Describes one state for a complex glazing system These input objects are typicall" +
                 "y generated by using WINDOW software and export to IDF syntax")]
    [JsonObject(Newtonsoft.Json.MemberSerialization.OptIn)]
    public class Construction_ComplexFenestrationState : BHoMObject, IEnergyPlusNode
    {
        

        [Description("This will be the main key of this instance. It will be the main key of the serial" +
                     "ization and all other properties will be sub properties of this key.")]
        [JsonProperty(PropertyName="name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string NodeName { get; set; } = "";
        

        [JsonProperty(PropertyName="basis_type", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Construction_ComplexFenestrationState_BasisType BasisType { get; set; } = (Construction_ComplexFenestrationState_BasisType)Enum.Parse(typeof(Construction_ComplexFenestrationState_BasisType), "LBNLWINDOW");
        

        [JsonProperty(PropertyName="basis_symmetry_type", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Construction_ComplexFenestrationState_BasisSymmetryType BasisSymmetryType { get; set; } = (Construction_ComplexFenestrationState_BasisSymmetryType)Enum.Parse(typeof(Construction_ComplexFenestrationState_BasisSymmetryType), "None");
        

        [JsonProperty(PropertyName="window_thermal_model", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string WindowThermalModel { get; set; } = "";
        

        [JsonProperty(PropertyName="basis_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string BasisMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="solar_optical_complex_front_transmittance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SolarOpticalComplexFrontTransmittanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="solar_optical_complex_back_reflectance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SolarOpticalComplexBackReflectanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="visible_optical_complex_front_transmittance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string VisibleOpticalComplexFrontTransmittanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="visible_optical_complex_back_transmittance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string VisibleOpticalComplexBackTransmittanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="outside_layer_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string OutsideLayerName { get; set; } = "";
        

        [JsonProperty(PropertyName="outside_layer_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string OutsideLayerDirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="outside_layer_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string OutsideLayerDirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="gap_1_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap1Name { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="cfs_gap_1_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CfsGap1DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="cfs_gap_1_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CfsGap1DirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_2_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer2Name { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_2_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer2DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_2_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer2DirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="gap_2_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap2Name { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="gap_2_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap2DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="gap_2_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap2DirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_3_material", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer3Material { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_3_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer3DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_3_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer3DirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="gap_3_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap3Name { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="gap_3_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap3DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="gap_3_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap3DirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_4_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer4Name { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_4_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer4DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_4_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer4DirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="gap_4_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap4Name { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="gap_4_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap4DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [Description("Reserved for future use. Leave it blank for this version")]
        [JsonProperty(PropertyName="gap_4_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Gap4DirectionalBackAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_5_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer5Name { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_5_directional_front_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer5DirectionalFrontAbsoptanceMatrixName { get; set; } = "";
        

        [JsonProperty(PropertyName="layer_5_directional_back_absoptance_matrix_name", NullValueHandling=Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Layer5DirectionalBackAbsoptanceMatrixName { get; set; } = "";
    }
}